-- AlterTable
ALTER TABLE "Cards" ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "cardImage" SET DATA TYPE TEXT,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User_Card" ALTER COLUMN "acquired_at" SET DEFAULT CURRENT_TIMESTAMP;
